### ISSUE TITLE
Change ID to not be a required argument

### ISSUE THREAD

**Issue by dmuso** [virtualshield/rails-graphql#33]
Hey! First up, I really like the concept of this gem, it's much more "Rails-like" than other GraphQL gems. 

I'm trying to use an ActiveRecord model as a source, but I need to make some tweaks so that I can query via a field other than ID. I notice from reading through the docs that I may be able to use `change_field` to make ID not required, but I can't quite get the syntax correct.

Here is code that works, if I'm querying a single record via ID:

app/graphql/myapp_schema.rb:
```
module GraphQL
  class MyAppSchema < GraphQL::Schema
    source Model
  end
end
```

GraphQL query:
```
query model($id: ID!) {
    model(id: $id) {
      id
      guid
    }
}
```

Result:
```
{"data":{"model":{"id":"1720000","guid":"568a248d-fd18-4a1d-aa5c-3a61230a4ee4"}}}
```

This all works fine, but when I want to query by a different field (`slug`):

GraphQL query:
```
query model($slug: String!) {
    model(slug: $slug) {
      id
      guid
      slug
    }
}
```

Result:
```
{"data":{},"errors":[{"message":"Invalid arguments for model field: the \"id\" argument can not be null.","locations":[{"line":1,"column":29},{"line":1,"column":66}],"path":["model","model"],"extensions":{"stage":"organize","exception":"Rails::GraphQL::ArgumentsError"}},{"message":"Variable $slug was provided to model query but not used.","locations":[{"line":1,"column":14},{"line":1,"column":27}],"path":["model"]}]}
```

So I do want my ActiveRecord source, but I want to override some properties so that I can make ID an optional argument. It's not clear from the docs exactly what's needed to achieve this, and I can't find any examples. 

I've tried something like this:
```
module GraphQL
  class MyAppSchema < GraphQL::Schema
    source Model do
      build_all
      change_field(:query, :id, null: true)
    end
  end
end
```

This gives me an error saying that `id` doesn't exist yet. I've tried many other variations of blocks, etc, to try and get it to work, but have so far been unsuccessful. 

Does anyone have any tips to point me in the right direction?

**Comment by crashtech** [comment]
Hey, Dan Harper! Thanks for the compliment. This gem has been a long-wanting project!

A little explanation from your code: `change_field` arguments are 1 - the type of the field and 2 - the name of the field. Your field's name, in that case, is `:model` (singular of your model. According to your description, you want to change the argument of a field.

Now, how to achieve that, you have several options. You have a more descriptive way of doing that:
```ruby
module GraphQL
  class MyAppSchema < GraphQL::Schema
    source Model do
      step(:query) do
        field(:model, 'Model', null: false) do
          argument(:slug, :id, null: false)
          on(:prepare) { |event| load_record(find_by: { slug: event.argument(:slug) }) }
        end
      end

      build_all
    end
  end
end
```

The idea is that you create the field before the automatic way can do it. Changing the argument name is insufficient because you must also change how the record will be found.

However, this will only change the query field, not the create/update/delete fields. If you want a more rounded option, you can do:
```ruby
module GraphQL
  class MyAppSchema < GraphQL::Schema
    source Model do
      def self.primary_key
        'slug'
      end

      build_all
    end
  end
end
```

This will make sure that slug is how your records are identified in all the ways. There are several other ways, so just let me know more specifically how many times and places you are going to need the change.

This gave me the idea to implement something like `identified_by :slug`, which would do something similar to overriding the primary key method.

**Comment by dmuso** [comment]
Awesome, thanks Carlos! I will try out some of these options and hopefully I can get it working. Our use case is a little unusual because we do actually have auto-incremented integer primary keys in our tables, which Rails likes out of the box, but we also have other systems that reference records via guids or slugs depending on the context.
